name: 🧠 Daily Animated AI Quote Update

on:
  schedule:
    - cron: "0 6 * * *" # runs daily at 6 AM UTC
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate & insert animated quote
        run: |
          set -euo pipefail

          # Array of motivational AI/data quotes
          QUOTES=(
            "Data is the new oil — pipelines are the refineries."
            "Automation is the present accelerated."
            "Every dataset hides a story — engineering reveals it."
            "Think in systems, act in data."
            "AI doesn’t replace engineers — it upgrades them."
            "From chaos to insight — one pipeline at a time."
            "Smart systems aren’t built — they’re engineered."
            "Data speaks only when engineered to."
          )

          RANDOM_QUOTE="${QUOTES[$RANDOM % ${#QUOTES[@]}]}"
          echo "Selected quote: $RANDOM_QUOTE"

          # If README doesn’t exist, create it
          if ! ls -1 | grep -iq '^readme'; then
            echo "No README found, creating README.md"
            echo "# Hi — I'm Lee Christmas" > README.md
            echo "" >> README.md
            echo "### 🧠 Daily AI Insight" >> README.md
            echo "<!--QUOTE-START-->" >> README.md
            echo "<!--QUOTE-END-->" >> README.md
            echo "" >> README.md
            echo "> *(auto-updates every day — powered by GitHub Actions)*" >> README.md
          fi

          README_FILE=$(ls -1 | grep -i '^readme' | head -n1)

          # Encode quote safely for SVG
          ENCODED=$(python3 - <<PY
import urllib.parse,sys
s="${RANDOM_QUOTE}"
print(urllib.parse.quote_plus(s))
PY
)

          SVG_LINE="<p align=\"center\"><img src=\"https://readme-typing-svg.herokuapp.com?font=Consolas&weight=700&size=24&duration=4500&pause=1000&color=00BFFF&center=true&vCenter=true&width=800&lines=${ENCODED}\" alt=\"AI Quote Animation\"></p>"

          # Replace quote block
          python3 - "$README_FILE" "$SVG_LINE" <<'PYCODE'
import sys
path, new = sys.argv[1], sys.argv[2]
text=open(path,encoding="utf-8").read()
start,end="<!--QUOTE-START-->","<!--QUOTE-END-->"
if start in text and end in text:
    pre,rest=text.split(start,1)
    _,post=rest.split(end,1)
    new_text=pre+start+"\n"+new+"\n"+end+post
else:
    new_text=text+"\n\n### 🧠 Daily AI Insight\n"+start+"\n"+new+"\n"+end+"\n"
if new_text!=text:
    open(path,"w",encoding="utf-8").write(new_text)
    print("Updated README with new quote.")
else:
    print("No changes needed.")
PYCODE

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add $(ls -1 | grep -i '^readme' | head -n1)
            git commit -m "🧠 Update daily AI insight"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
