name: Generate Heartbeat Palette

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install gitfiti
        run: |
          git clone https://github.com/gelstudios/gitfiti.git
          cd gitfiti
          pip install -r requirements.txt

      - name: Generate Heartbeat Pattern
        run: |
          cd gitfiti
          cat <<'EOF' > heartbeat.txt
          _   _            _    _            _    
         | | | | ___  __ _| | _| | ___   ___| | __
         | |_| |/ _ \/ _` | |/ / |/ _ \ / __| |/ /
         |  _  |  __/ (_| |   <| | (_) | (__|   < 
         |_| |_|\___|\__,_|_|\_\_|\___/ \___|_|\_\
          EOF

          python gitfiti.py -m heartbeat.txt -o ../preview/heartbeat-preview.png --no-prompt

      - name: Commit Heartbeat Preview
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "❤️ Update Heartbeat Preview"
          file_pattern: preview/heartbeat-preview.png
