name: Generate Heartbeat Palette

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install gitfiti
        run: |
          git clone https://github.com/gelstudios/gitfiti.git
          cd gitfiti
          pip install -r requirements.txt

      - name: Generate Heartbeat Pattern
        run: |
          mkdir -p preview
          cd gitfiti
          cat <<'EOF' > heartbeat.txt
  __  __     _        _    _                _   
 |  \/  | __| |_   _ | |__(_)_ __ ___   ___| |_ 
 | |\/| |/ _` | | | || '_ \| | '_ ` _ \ / _ \ __|
 | |  | | (_| | |_| || |_) | | | | | | |  __/ |_ 
 |_|  |_|\__,_|\__, ||_.__/|_|_| |_| |_|\___|\__|
               |___/                             
          EOF
          python gitfiti.py -m heartbeat.txt -o ../preview/heartbeat-preview.png --no-prompt

      - name: Commit Heartbeat Preview
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "❤️ Update Heartbeat Preview"
          file_pattern: preview/heartbeat-preview.png
